### ISSUE TITLE
Feature Request: 5 day Weather Forecast

### ISSUE THREAD

**Issue by CeJienAJPC** [igormatyushkin014/F32-for-Android#1]

**Comment by igormatyushkin014** [comment]
@CeJienAJPC Try this https://github.com/igormatyushkin014/F32-for-Android#forecast

Don't forget to update your Gradle dependency: `compile 'com.visuality.f32forandroid:f32:1.2'`

**Comment by CeJienAJPC** [comment]
Thanks for the upgrade.
