### ISSUE TITLE
No humidity and pressure properties

### ISSUE THREAD

**Issue by ffleandro** [igormatyushkin014/F32-for-Android#3]
The `Weather` object has no humidity or pressure information.
According to the API this information comes in the main object: http://samples.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a1

**Comment by ffleandro** [comment]
From what I've seen, the `AtmosphericInformation` has already been added to the repository, however it has not been deployed to `jcenter`.

Could you please deploy a new version?

**Comment by igormatyushkin014** [comment]
@ffleandro Example of usage:
```java
/*
 * Pressure.
 */

long pressure = weather.getAtmosphere().getPressure();

/*
 * Humidity.
 */

int humidityPercentage = weather.getAtmosphere().getHumidity();
```

Update your Gradle dependency:

```
compile 'com.visuality.f32forandroid:f32:2.2'
```

**Comment by igormatyushkin014** [comment]
@ffleandro Example of usage:
```java
/*
 * Pressure.
 */

long pressure = weather.getAtmosphere().getPressure();

/*
 * Humidity.
 */

int humidityPercentage = weather.getAtmosphere(). getHumidityPercentage();
```

Update your Gradle dependency:

```
compile 'com.visuality.f32forandroid:f32:2.2'
```

**Comment by igormatyushkin014** [comment]
@ffleandro Example of usage:
```java
/*
 * Pressure.
 */

long pressure = weather.getAtmosphere().getPressure();

/*
 * Humidity.
 */

int humidityPercentage = weather.getAtmosphere().getHumidityPercentage();
```

Update your Gradle dependency:

```
compile 'com.visuality.f32forandroid:f32:2.2'
```

**Comment by ffleandro** [comment]
Thanks for deploying new version.
Cheers.
